### ISSUE TITLE
[meta] Get Involved

### ISSUE THREAD

**Issue by rufuspollock** [rgrp/cop21#11]
We want and welcome help! Anyone can contribute and you don't need major technical skills.

We need help with various things from:
- [x] #8 Adding annotation - small bit of JS knowledge
- [x] #2 Proof editing the markdown - just text editing, markdown and looking at the original PDFs
- [ ] Updating with new negotiating text [when it comes out](http://unfccc.int/meetings/paris_nov_2015/items/9326.php)
- [ ] #9 visual comparison of different versions
- [ ] Promoting the project - we need to tell relevant parties including delegates, journalists, CSOs and others that the site exists and they can use it ...

If you are interested please just drop a comment below.
